backend:
  name: git-gateway
  branch: main
media_folder: "/src/assets/blog"
public_folder: "/assets/blog"
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "string" }
      - { label: "Autor/a", name: "author", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Etiquetas", name: "tags", widget: "list", default: ["post"] }
      - { label: "Imagen destacada", name: "image", widget: "image" }
      - { label: "Descripción de la imagen", name: "imageAlt", widget: "string" }
      - { label: "Cuerpo del artículo", name: "body", widget: "markdown" }
